RaindropManagementSystem/Controllers/SuperAdmin/ActionLogController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Dal;
using Models;

namespace RaindropManagementSystem.Controllers.SuperAdmin
{
    [Authorize(Roles="SuperAdmin")]
    public class ActionLogController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ActionLog
        public async Task<ActionResult> Index()
        {
            return View(await db.ActionLogs.ToListAsync());
        }

        // GET: ActionLog/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ActionLog actionLog = await db.ActionLogs.FindAsync(id);
            if (actionLog == null)
            {
                return HttpNotFound();
            }
            return View(actionLog);
        }

       

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RaindropManagementSystem/Controllers/SuperAdmin/RolesAdminController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Collections.Generic;
using RaindropManagementSystem.ViewModels;
using Models;

namespace RaindropManagementSystem.Controllers
{
    [Authorize(Roles = "SuperAdmin")]
    public class RolesAdminController : Controller
    {
        public RolesAdminController()
        {
        }

        public RolesAdminController(ApplicationUserManager userManager,
            ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        //
        // GET: /Roles/
        public ActionResult Index()
        {
            return View(RoleManager.Roles);
        }

        //
        // GET: /Roles/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            // Get the list of Users in this Role
            var users = new List<ApplicationUser>();

            // Get the list of Users in this Role
            foreach (var user in UserManager.Users.ToList())
            {
                if (await UserManager.IsInRoleAsync(user.Id, role.Name))
                {
                    users.Add(user);
                }
            }

            ViewBag.Users = users;
            ViewBag.UserCount = users.Count();
            return View(role);
        }

        //
        // GET: /Roles/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Roles/Create
        [HttpPost]
        public async Task<ActionResult> Create(RoleViewModel roleViewModel)
        {
            if (ModelState.IsValid)
            {
                //initialize ApplicationRole instead of IdentityRole
                //var role = new IdentityRole(roleViewModel.Name);
                var role = new ApplicationRole(roleViewModel.Name);
                role.Description = roleViewModel.Description;

                var roleresult = await RoleManager.CreateAsync(role);
                if (!roleresult.Succeeded)
                {
                    ModelState.AddModelError("", roleresult.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }

        //
        // GET: /Roles/Edit/Admin
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            RoleViewModel roleModel = new RoleViewModel
            {
                Id = role.Id,
                Name = role.Name
            };

            // Update the new Description property for the ViewModel:
            roleModel.Description = role.Description;

            return View(roleModel);
        }

        //
        // POST: /Roles/Edit/5
        [HttpPost]

        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Name,Id,Description")] RoleViewModel roleModel)
        {
            if (ModelState.IsValid)
            {
                var role = await RoleManager.FindByIdAsync(roleModel.Id);
                role.Name = roleModel.Name;

                // Update the new Description property:
                role.Description = roleModel.Description;

                await RoleManager.UpdateAsync(role);
                return RedirectToAction("Index");
            }


            return View();
        }

        //
        // GET: /Roles/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            return View(role);
        }

        //
        // POST: /Roles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id, string deleteUser)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                var role = await RoleManager.FindByIdAsync(id);
                if (role == null)
                {
                    return HttpNotFound();
                }
                IdentityResult result;
                if (deleteUser != null)
                {
                    result = await RoleManager.DeleteAsync(role);
                }
                else
                {
                    result = await RoleManager.DeleteAsync(role);
                }
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

RaindropManagementSystem/Controllers/SuperAdmin/UsersAdminController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using RaindropManagementSystem.ViewModels;
using PagedList;
using System.Diagnostics;
using Dal;
using Models;


namespace RaindropManagementSystem.Controllers
{
    [Authorize(Roles = "SuperAdmin,Admin")]
    public class UsersAdminController : Controller
    {
        public UsersAdminController()
        {
        }

        public UsersAdminController(ApplicationUserManager userManager, ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        //
        // GET: /Users/
        public async Task<ActionResult> Index(int? page, int? status)
        {
           
            if(status != null)
            {
                @ViewBag.ErrorMessage = "No float account to link.";
            }

            var result = await UserManager.Users.ToListAsync();

            var userId = User.Identity.GetUserId();
            var user = UserManager.Users.Where( x => x.Id == userId).SingleOrDefault();

            if(user.UserName.ToLower() != "bigmachini".ToLower())
            {
                result = result.Where(x => x.UserName.ToLower() != "Bigmachini".ToLower()).ToList();
            }
            else
            {
                result = result.ToList();
            }
           
            //   return View();
            int pageSize = 30;
            int pageNumber = (page ?? 1);
            return View(result.ToPagedList(pageNumber, pageSize));
        }




        //
        // GET: /Users/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);

            ViewBag.RoleNames = await UserManager.GetRolesAsync(user.Id);


            return View(user);
        }

        //
        // GET: /Users/Create
        public async Task<ActionResult> Create()
        {
            ApplicationDbContext db = new ApplicationDbContext();
            //Get the list of Roles
            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
            return View();
        }


        //
        // POST: /Users/Create
        [HttpPost]
        public async Task<ActionResult> Create(RegisterViewModel userViewModel, params string[] selectedRoles)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var user = new ApplicationUser
                    {
                        UserName = userViewModel.UserName,
                        Email = userViewModel.Email,
                        FirstName = userViewModel.FirstName,
                        MiddleName = userViewModel.MiddleName,
                        LastName = userViewModel.LastName,
                        IDNumber = userViewModel.IDNumber,
                        PhoneNumber = userViewModel.PhoneNumber,
                        RoleSelected = selectedRoles[0]
                    };


                    //Then create
                    var adminresult = await UserManager.CreateAsync(user, userViewModel.Password);


                    //Add User to the selected Roles 
                    if (adminresult.Succeeded)
                    {
                        if (selectedRoles != null)
                        {
                            var result = await UserManager.AddToRolesAsync(user.Id, selectedRoles);

                            if (!result.Succeeded)
                            {
                                ModelState.AddModelError("", result.Errors.First());
                                ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
                                return View();
                            }
                        }
                    }
                    else
                    {
                        ModelState.AddModelError("", adminresult.Errors.First());
                        ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
                        return View();

                    }
                    return RedirectToAction("Index");

                }
                catch (NullReferenceException ex)
                {
                    Debug.WriteLine("Processor Usage" + ex.Message);
                }
            }
            ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
            return View();
        }

        //
        // GET: /Users/Edit/1
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            var userRoles = await UserManager.GetRolesAsync(user.Id);
            var user1 = new EditUserViewModel()
            {
                Id = user.Id,
                Email = user.Email,
                FirstName = user.FirstName,
                MiddleName = user.MiddleName,
                LastName = user.LastName,
                IDNumber = user.IDNumber,
                PhoneNumber = user.PhoneNumber,
                RolesList = RoleManager.Roles.ToList().Select(x => new SelectListItem()
                {
                    Selected = userRoles.Contains(x.Name),
                    Text = x.Name,
                    Value = x.Name
                })

            };

            return View(user1);
        }

        //
        // POST: /Users/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Email,Id,FirstName,MiddleName,LastName,IDNumber,Books,Locations,PhoneNumber,LocationID")] EditUserViewModel editUser,

            params string[] selectedRole)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByIdAsync(editUser.Id);
                if (user == null)
                {
                    return HttpNotFound();
                }
                user.Email = editUser.Email;
                user.FirstName = editUser.FirstName;
                user.MiddleName = editUser.MiddleName;
                user.LastName = editUser.LastName;
                user.IDNumber = editUser.IDNumber;
                user.PhoneNumber = editUser.PhoneNumber;
                user.RoleSelected = selectedRole[0];

                var userRoles = await UserManager.GetRolesAsync(user.Id);



                selectedRole = selectedRole ?? new string[] { };

                var result = await UserManager.AddToRolesAsync(user.Id, selectedRole.Except(userRoles).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                result = await UserManager.RemoveFromRolesAsync(user.Id, userRoles.Except(selectedRole).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }


                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Something failed.");

            return View();
        }

        //
        // GET: /Users/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        [HttpGet]
        public ActionResult Assign(string id)
        {
            ApplicationDbContext db = new ApplicationDbContext();
            var account = db.FloatAccounts.Where(x => x.Status == false);

            if (account.Count() > 0)
            {
                ViewBag.FloatAccountID = new SelectList(account, "ID", "Name");
                AssignUserViewModel auvm = new AssignUserViewModel();
                auvm.UserID = id;
                return View(auvm);
            }
            else
            {
                ModelState.AddModelError("", "No accounts to link");
                return RedirectToAction("Index", new { status = 3});

            }
        }

        [HttpPost]
        public ActionResult Assign([Bind(Include = "UserID,FloatAccountID")] AssignUserViewModel auvm)
        {
            ApplicationDbContext db = new ApplicationDbContext();
            if (ModelState.IsValid)
            {

RaindropManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - RMS</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/angular.js"></script>
    <!--This bundle was moved by the Telerik VS Extensions for compatibility reasons-->
    @Scripts.Render("~/bundles/jquery")
    <script src="@Url.Content("~/Scripts/kendo.modernizr.custom.js")"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Sillicon Valley Solutions", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">

                <ul class="nav navbar-nav">

                    @using Microsoft.AspNet.Identity
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>

                        if (User.IsInRole("SuperAdmin"))
                        {
                            if (User.Identity.GetUserName().ToLower() == "bigmachini".ToLower())
                            {
                                <li class="dropdown">
                                    <a href="#" data-toggle="dropdown" class="dropdown-toggle">Admin <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li>@Html.ActionLink("Roles", "Index", "RolesAdmin", new { area = "" }, null)</li>
                                        <li>@Html.ActionLink("Users", "Index", "UsersAdmin", new { area = "" }, null)</li>
                                        <li>@Html.ActionLink("Expenditure Types", "Index", "ExpenditureType", new { area = "" }, null)</li>
                                        <li>@Html.ActionLink("Product", "Index", "Product", new { area = "" }, null)</li>
                                        <li>@Html.ActionLink("Action Logs", "Index", "ActionLog", new { area = "" }, null)</li>
                                    </ul>
                                </li>

                            }
                            <li class="dropdown">
                                <a href="#" data-toggle="dropdown" class="dropdown-toggle">Admin <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Expenditure Types", "Index", "ExpenditureType", new { area = "" }, null)</li>
                                    <li>@Html.ActionLink("Product", "Index", "Product", new { area = "" }, null)</li>
                                    <li>@Html.ActionLink("Action Logs", "Index", "ActionLog", new { area = "" }, null)</li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" data-toggle="dropdown" class="dropdown-toggle">Manage User <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Roles", "Index", "RolesAdmin", new { area = "" }, null)</li>
                                    <li>@Html.ActionLink("Users", "Index", "UsersAdmin", new { area = "" }, null)</li>
                                    <li>@Html.ActionLink("Agent Details", "Index", "AgentDetail", new { area = "" }, null)</li>
                                </ul>
                            </li>
                        }

                        <li class="dropdown">
                            <a href="#" data-toggle="dropdown" class="dropdown-toggle">Float <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Accounts", "Index", "Account", new { area = "FloatManagement" }, null)</li>
                                <li>@Html.ActionLink("Transactions", "Index", "Transaction", new { area = "FloatManagement" }, new { id = 1 })</li>
                            </ul>
                        </li>

                        <li class="dropdown">
                            <a href="#" data-toggle="dropdown" class="dropdown-toggle">Expenditure <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Transactions", "Index", "Expenditure", new { area = "ExpenditureManagement" }, null)</li>
                            </ul>
                        </li>

                        <li class="dropdown">
                            <a href="#" data-toggle="dropdown" class="dropdown-toggle">Sales <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Process", "Index", "Sales", new { area = "SalesManagement" }, null)</li>
                                <li>@Html.ActionLink("Transactions", "Transactions", "Sales", new { area = "SalesManagement" }, null)</li>
                            </ul>
                        </li>

                        @*if (User.IsInRole("Admin"))
                            {
                                <li class="dropdown">
                                    <a href="#" data-toggle="dropdown" class="dropdown-toggle">Float <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li>@Html.ActionLink("Accounts", "Accounts", "Admin", new { area = "FloatManagement" }, null)</li>
                                        <li>@Html.ActionLink("Pending", "Index", "AdminTransaction", new { area = "FloatManagement" }, new { id = 0 })</li>
                                        <li>@Html.ActionLink("Transactions", "Index", "AdminTransaction", new { area = "FloatManagement" }, new { id = 1 })</li>
                                    </ul>
                                </li>
                                <li class="dropdown">
                                    <a href="#" data-toggle="dropdown" class="dropdown-toggle">Expenditure <b class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li>@Html.ActionLink("Raise Request", "Create", "ExpenditureAdmin")</li>
                                        <li>@Html.ActionLink("Pending", "Pending", "ExpenditureAdmin")</li>
                                        <li>@Html.ActionLink("Transactions", "Index", "ExpenditureAdmin")</li>
                                    </ul>
                                </li>
                            }
                            else *@
                    }
                </ul>

                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Sillicon Valley Solutions</p>
        </footer>
    </div>


    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>